services:
  scrunk:
    container_name: scrunkwebcontainer
    build: .
    image: scrunk:latest
    ports:
      - "9696:8080"
    expose:
      - 8080
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge