services:
  scrunk:
    container_name: scrunkwebcontainer
    build: .
    image: scrunk:latest
    ports:
      - "40080:40080"
    expose:
      - 40080
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge